name: Docker Image Build and Push CI CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v1     
      with:       
        username: ${{ secrets.DOCKER_HUB_USERNAME }} 
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: 76759398/sprint-boot-helloworld    
        tags: latest
    - name: Create a cluster
      uses: AbsaOSS/k3d-action@v1.4.0
      with:
        cluster-name: test
        args: >-
          --config k3d.yaml
    - name: Deploy the app
      run: |
        kubectl apply -f sprint-boot-helloworld.yaml
    - name: Test
      run: |
        kubectl run test --image alpine -i --restart Never -- sh -c "apk add --update curl && curl sprint-boot-helloworld:8080"
  

