name: Docker Image Build and Push CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v1     
      with:       
        username: ${{ secrets.DOCKER_HUB_USERNAME }} 
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: 76759398/sprint-boot-helloworld    
        tags: latest
  

